"""empty message

Revision ID: 115b8d413c1b
Revises: 216fa45ddc99
Create Date: 2021-01-15 13:14:25.379773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115b8d413c1b'
down_revision = '216fa45ddc99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waypoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ident_public_key', sa.String(length=6), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('compass', sa.Integer(), nullable=True),
    sa.Column('altitude', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ident_public_key'], ['plane.ident_public_key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('waypoint')
    # ### end Alembic commands ###
